### ISSUE TITLE
Can't install it using pip

### ISSUE THREAD

**Issue by x0y-gt** [twyla-ai/aiographql-client#90] opened 2020-03-09 12:22 UTC
I'm receiving this error trying to install it
```
> pip install aiographql-client
ERROR: Could not find a version that satisfies the requirement aiographql-client (from versions: none)
ERROR: No matching distribution found for aiographql-client
```

**Comment by abn** [comment] 2020-03-09 16:52
@x0y-gt it might be that the default python is pointing to 2.x? This library only supports 3.7 and later at the moment. Additionally you might also want to install the pre-release version as the older versions do not match the documentation. A 1.0.0 release is expected this week.

You can try:
```sh
pip3 install --pre aiographql-client
```

**Comment by abn** [comment] 2020-03-15 14:38
Closing as this does not seem to be a packaging issue, but rather an environment issue. If the issue is not resolved, please feel free to re-open with more information.

**Closed by abn** 2020-03-15 14:38 UTC
